[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Beforerr = "49aed396-608e-4c3f-b6d6-a749216c9ea7"
CDAWeb = "950ff2a9-823f-469c-91a7-754a5d85edca"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CommonDataFormat = "a9737db6-c05c-4e48-868b-6bc41491d9d9"
ContinuousWavelets = "96eb917e-2868-4417-9cb6-27e7ff17528f"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PlasmaFormulary = "d26ff896-aba2-4e70-a0a6-448627456efe"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
PySPEDAS = "668d2cef-03a7-4c36-a521-7d1c6ddc8846"
SPEDAS = "3930f61c-4d81-4846-ab8f-357babe068a6"
SignalAnalysis = "df1fea92-c066-49dd-8b36-eace3378ea47"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
SpacePhysicsMakie = "0c28ffd8-ae30-4a56-b2e4-f8332c621ad2"
SpaceWeather = "6e6210c8-0d11-4989-92a2-df0be76561ad"
Speasy = "09b745ad-c67d-442f-94a6-c7f4d1e4d861"
SummaryTables = "6ce4ecf0-73a7-4ce3-9fb4-80ebfe887b60"
TimeseriesUtilities = "31d49243-0742-49c1-b8d2-db113b74581e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
